server:
  port: 8200
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:customersDB
    driver-class-name: org.h2.Driver
    username: sa
    password: customer@Test
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka},${EUREKA_URI:http://localhost:8762/eureka}
    instance:
      preferIpAddress: true
