server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8100/
          predicates:
            - path: /customers/**
        - id: acoounts-service
          uri: http://localhost:8200/
          predicates:
            - path: /accounts/**
