server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: customerService
        uri: lb://customer-service
        predicates:
        - Path=/customers/**
      - id: acoountsService
        uri: lb://account-service
        predicates:
        - Path=/accounts/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/