server:
  port: 8762
eureka:
  instance:
    hostname: service-registry2
    appname: service-registry
  environment: local
  client:
    service-url:
      defaultZone: http://service-registry1:8761/eureka
    register-with-eureka: true
    fetch-registry: true