spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:mem:accountsDB
    driver-class-name: org.h2.Driver
    username: sa
    password: account@Test
  h2:
    console:
      enabled: true
server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka},${EUREKA_URI:http://localhost:8762/eureka}
    instance:
      preferIpAddress: true
